on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: 'testing github action'
        run: pwd 


    steps:
      - name: 'testing printing '
        run: echo nobil 



